# Generated by Django 2.2.3 on 2019-07-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillset', models.IntegerField(choices=[(1, 'PYTHON'), (2, 'JAVA'), (3, 'PHP'), (4, 'DOT_NET'), (5, 'C')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('profile', models.ManyToManyField(blank=True, to='Userapp.Profile')),
            ],
        ),
    ]
