# Generated by Django 2.2.3 on 2019-07-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skillset',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Userapp.User'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_profile',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
